"""added_status_column_for_tasks

Revision ID: 0fedbe8b7cb0
Revises: e45880fc248f
Create Date: 2021-12-28 08:07:11.997609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fedbe8b7cb0'
down_revision = 'e45880fc248f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
