"""adding taskers table

Revision ID: 81525775b42e
Revises: d3bf5ef99841
Create Date: 2021-12-14 18:40:01.938380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81525775b42e'
down_revision = 'd3bf5ef99841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('taskTypesId', sa.Integer(), nullable=False),
    sa.Column('citiesId', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['citiesId'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['taskTypesId'], ['taskTypes.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taskers')
    # ### end Alembic commands ###
