"""adding_status_for_tasker

Revision ID: e45880fc248f
Revises: 19c9ff5310cc
Create Date: 2021-12-28 08:03:09.716546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45880fc248f'
down_revision = '19c9ff5310cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskers', sa.Column('status', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taskers', 'status')
    # ### end Alembic commands ###
